export const apiUrls = {
products:'/products/items',
reportProduct : '/products/report-found',
getAllClaims : '/products/claim',
getClaimDetailsByID : '/products/claim',
updateClaimDetailsById : '/products/claim',
claimItemById : '/products/claim',
getClaimByUser : '/products/claims/user',
login: '/auth/login',
addNewUser: '/auth/users',
getAllUsers: '/auth/users',
getUserDetails: '/auth/users',
updateUserDetailsById: '/auth/users', 
resetPassword: '/api/admin/reset-password',
verifyOtp: '/api/admin/verify-otp',
categories: '/categories',
}