export const apiUrls = {
products:'/products/items',
reportProduct : '/products/report-found',
getAllClaims : '/products/claim',
getClaimDetailsByID : '/products/claim',
updateClaimDetailsById : '/products/claim',
claimItemById : '/products/claim',
getClaimByUser : '/products/claims/user',
login: '/auth/login',
forgotPassword: '/auth/forgot-password',
addNewUser: '/auth/users',
getAllUsers: '/auth/users',
getUserDetails: '/auth/users',
updateUserDetailsById: '/auth/users', 
resetPassword: '/auth/reset-password',
verifyOtp: '/auth/verify-otp',
categories: '/categories',
imageUpload: '/files/upload',
imageDelete: '/files/delete',
getAnalytics: '/products/dashboard/analytics'
}