
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/app.scss";
// import { ReduxProvider } from "./store/provider";
import  Provider  from "./store/provider";
import { store } from "./store/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Provider >
        {children}
        </Provider>
      </body>
    </html>
  );
}
